AllCops:
  TargetRubyVersion: 2.5.6

require:
  - rubocop-rspec
  - rubocop-performance

Metrics/MethodLength:
  Exclude:
    - 'features/support/env.rb'

Metrics/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
