AllCops:
  TargetRubyVersion: 2.6.5

require:
  - rubocop-rspec
  - rubocop-performance

Metrics/BlockLength:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
